# Streamlit Secrets (add in the platform's UI)
OPENAI_API_KEY = "sk-..."
# OPENAI_BASE_URL = "https://api.openai.com/v1"
# MODEL = "gpt-4o-mini"

# Optional STT model name for /audio/transcriptions
# WHISPER_MODEL = "whisper-1"

# Optional Supabase
# SUPABASE_URL = "https://xxxx.supabase.co"
# SUPABASE_KEY = "eyJhbGci..."

# Optional local DB path (for SQLite). On Streamlit Cloud a temp path is fine.
# ALISA_DB_PATH = "alisa.db"
